package Formularios;

import tel.Cliente;

/**
 *
 * @author SE31452
 */
public class BuscarCliente extends javax.swing.JInternalFrame {

    /**
     * Creates new form BuscarCliente
     */
    public BuscarCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblBuscarClienteTitulo = new javax.swing.JLabel();
        lblBuscarTelefono = new javax.swing.JLabel();
        lblBuscarDni = new javax.swing.JLabel();
        lblBuscarApellido = new javax.swing.JLabel();
        lblBuscarNombre = new javax.swing.JLabel();
        lblBuscarCiudad = new javax.swing.JLabel();
        lblBuscarDireccion = new javax.swing.JLabel();
        txtBuscarTelefono = new javax.swing.JTextField();
        txtBuscarDni = new javax.swing.JTextField();
        txtBuscarApellido = new javax.swing.JTextField();
        txtBuscarNombre = new javax.swing.JTextField();
        txtBuscarCiudad = new javax.swing.JTextField();
        txtBuscarDireccion = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        btnBuscarNuevo = new javax.swing.JButton();
        btnBuscarSalir = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("Buscar Cliente");

        lblBuscarClienteTitulo.setFont(new java.awt.Font("Dialog", 2, 18)); // NOI18N
        lblBuscarClienteTitulo.setForeground(new java.awt.Color(102, 102, 255));
        lblBuscarClienteTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBuscarClienteTitulo.setText("Buscar Cliente");
        lblBuscarClienteTitulo.setToolTipText("");

        lblBuscarTelefono.setText("Telefono");

        lblBuscarDni.setText("DNI");

        lblBuscarApellido.setText("Apellido");

        lblBuscarNombre.setText("Nombre");

        lblBuscarCiudad.setText("Ciudad");

        lblBuscarDireccion.setText("Direccion");

        txtBuscarDni.setEditable(false);

        txtBuscarApellido.setEditable(false);

        txtBuscarNombre.setEditable(false);

        txtBuscarCiudad.setEditable(false);

        txtBuscarDireccion.setEditable(false);

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnBuscarNuevo.setText("Nuevo");
        btnBuscarNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarNuevoActionPerformed(evt);
            }
        });

        btnBuscarSalir.setText("Salir");
        btnBuscarSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblBuscarClienteTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(91, 91, 91))
            .addGroup(layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(btnBuscar)
                        .addGap(18, 18, 18)
                        .addComponent(btnBuscarNuevo)
                        .addGap(18, 18, 18)
                        .addComponent(btnBuscarSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblBuscarTelefono)
                            .addComponent(lblBuscarDni)
                            .addComponent(lblBuscarApellido)
                            .addComponent(lblBuscarNombre)
                            .addComponent(lblBuscarCiudad)
                            .addComponent(lblBuscarDireccion))
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtBuscarTelefono)
                            .addComponent(txtBuscarDni)
                            .addComponent(txtBuscarApellido)
                            .addComponent(txtBuscarNombre)
                            .addComponent(txtBuscarCiudad)
                            .addComponent(txtBuscarDireccion, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE))))
                .addContainerGap(67, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblBuscarClienteTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBuscarTelefono)
                    .addComponent(txtBuscarTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBuscarDni)
                    .addComponent(txtBuscarDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBuscarApellido)
                    .addComponent(txtBuscarApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBuscarNombre)
                    .addComponent(txtBuscarNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBuscarCiudad)
                    .addComponent(txtBuscarCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBuscarDireccion)
                    .addComponent(txtBuscarDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBuscar)
                    .addComponent(btnBuscarNuevo)
                    .addComponent(btnBuscarSalir))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarNuevoActionPerformed
        // TODO add your handling code here:
        txtBuscarApellido.setText("");
        txtBuscarCiudad.setText("");
        txtBuscarTelefono.setText("");
        txtBuscarDireccion.setText("");
        txtBuscarDni.setText("");
        txtBuscarNombre.setText("");
        txtBuscarTelefono.requestFocus();
    }//GEN-LAST:event_btnBuscarNuevoActionPerformed

    private void btnBuscarSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarSalirActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnBuscarSalirActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        String telefono = txtBuscarTelefono.getText();
        Cliente buscado = principal.miDirectorio.buscarCliente(telefono);
        txtBuscarApellido.setText(buscado.getApellido());
        txtBuscarCiudad.setText(buscado.getCiudad());
        txtBuscarDireccion.setText(buscado.getDireccion());
        txtBuscarDni.setText(buscado.getDni()+"");
        txtBuscarNombre.setText(buscado.getNombre());
    }//GEN-LAST:event_btnBuscarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnBuscarNuevo;
    private javax.swing.JButton btnBuscarSalir;
    private javax.swing.JLabel lblBuscarApellido;
    private javax.swing.JLabel lblBuscarCiudad;
    private javax.swing.JLabel lblBuscarClienteTitulo;
    private javax.swing.JLabel lblBuscarDireccion;
    private javax.swing.JLabel lblBuscarDni;
    private javax.swing.JLabel lblBuscarNombre;
    private javax.swing.JLabel lblBuscarTelefono;
    private javax.swing.JTextField txtBuscarApellido;
    private javax.swing.JTextField txtBuscarCiudad;
    private javax.swing.JTextField txtBuscarDireccion;
    private javax.swing.JTextField txtBuscarDni;
    private javax.swing.JTextField txtBuscarNombre;
    private javax.swing.JTextField txtBuscarTelefono;
    // End of variables declaration//GEN-END:variables
}
